"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class DeleteQueueMessageMessageIDQueueType(str, Enum):
    MAIN = "main"
    PROCESSING = "processing"
    DEAD = "dead"
    ARCHIVE = "archive"


class DeleteQueueMessageMessageIDRequestBodyTypedDict(TypedDict):
    r"""Queue Type"""

    queue_type: DeleteQueueMessageMessageIDQueueType


class DeleteQueueMessageMessageIDRequestBody(BaseModel):
    r"""Queue Type"""

    queue_type: Annotated[
        DeleteQueueMessageMessageIDQueueType, pydantic.Field(alias="queueType")
    ]


class DeleteQueueMessageMessageIDRequestTypedDict(TypedDict):
    message_id: str
    request_body: DeleteQueueMessageMessageIDRequestBodyTypedDict
    r"""Queue Type"""


class DeleteQueueMessageMessageIDRequest(BaseModel):
    message_id: Annotated[
        str,
        pydantic.Field(alias="messageId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    request_body: Annotated[
        DeleteQueueMessageMessageIDRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Queue Type"""


class DeleteQueueMessageMessageIDResponseTypedDict(TypedDict):
    r"""Message Deleted"""

    success: bool
    message_id: str
    queue_type: str
    message: str


class DeleteQueueMessageMessageIDResponse(BaseModel):
    r"""Message Deleted"""

    success: bool

    message_id: Annotated[str, pydantic.Field(alias="messageId")]

    queue_type: Annotated[str, pydantic.Field(alias="queueType")]

    message: str
