"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Any, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class MainQueueMessageTypedDict(TypedDict):
    id: str
    type: str
    created_at: float
    attempt_count: float
    dequeued_at: Nullable[float]
    last_error: Nullable[str]
    processing_duration: float
    payload: NotRequired[Nullable[Any]]
    priority: NotRequired[float]


class MainQueueMessage(BaseModel):
    id: str

    type: str

    created_at: float

    attempt_count: float

    dequeued_at: Nullable[float]

    last_error: Nullable[str]

    processing_duration: float

    payload: OptionalNullable[Any] = UNSET

    priority: Optional[float] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["payload", "priority"]
        nullable_fields = ["payload", "dequeued_at", "last_error"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


class MainQueueTypedDict(TypedDict):
    name: str
    length: float
    messages: List[MainQueueMessageTypedDict]


class MainQueue(BaseModel):
    name: str

    length: float

    messages: List[MainQueueMessage]


class ProcessingQueueMessageTypedDict(TypedDict):
    id: str
    type: str
    created_at: float
    attempt_count: float
    dequeued_at: Nullable[float]
    last_error: Nullable[str]
    processing_duration: float
    payload: NotRequired[Nullable[Any]]
    priority: NotRequired[float]


class ProcessingQueueMessage(BaseModel):
    id: str

    type: str

    created_at: float

    attempt_count: float

    dequeued_at: Nullable[float]

    last_error: Nullable[str]

    processing_duration: float

    payload: OptionalNullable[Any] = UNSET

    priority: Optional[float] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["payload", "priority"]
        nullable_fields = ["payload", "dequeued_at", "last_error"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


class ProcessingQueueTypedDict(TypedDict):
    name: str
    length: float
    messages: List[ProcessingQueueMessageTypedDict]


class ProcessingQueue(BaseModel):
    name: str

    length: float

    messages: List[ProcessingQueueMessage]


class DeadLetterQueueMessageTypedDict(TypedDict):
    id: str
    type: str
    created_at: float
    attempt_count: float
    dequeued_at: Nullable[float]
    last_error: Nullable[str]
    processing_duration: float
    payload: NotRequired[Nullable[Any]]
    priority: NotRequired[float]


class DeadLetterQueueMessage(BaseModel):
    id: str

    type: str

    created_at: float

    attempt_count: float

    dequeued_at: Nullable[float]

    last_error: Nullable[str]

    processing_duration: float

    payload: OptionalNullable[Any] = UNSET

    priority: Optional[float] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["payload", "priority"]
        nullable_fields = ["payload", "dequeued_at", "last_error"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


class DeadLetterQueueTypedDict(TypedDict):
    name: str
    length: float
    messages: List[DeadLetterQueueMessageTypedDict]


class DeadLetterQueue(BaseModel):
    name: str

    length: float

    messages: List[DeadLetterQueueMessage]


class ArchiveQueueMessageTypedDict(TypedDict):
    id: str
    type: str
    created_at: float
    attempt_count: float
    dequeued_at: Nullable[float]
    last_error: Nullable[str]
    processing_duration: float
    payload: NotRequired[Nullable[Any]]
    priority: NotRequired[float]


class ArchiveQueueMessage(BaseModel):
    id: str

    type: str

    created_at: float

    attempt_count: float

    dequeued_at: Nullable[float]

    last_error: Nullable[str]

    processing_duration: float

    payload: OptionalNullable[Any] = UNSET

    priority: Optional[float] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["payload", "priority"]
        nullable_fields = ["payload", "dequeued_at", "last_error"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


class ArchiveQueueTypedDict(TypedDict):
    name: str
    length: float
    messages: List[ArchiveQueueMessageTypedDict]


class ArchiveQueue(BaseModel):
    name: str

    length: float

    messages: List[ArchiveQueueMessage]


class MetadataTypedDict(TypedDict):
    total_processed: float
    total_failed: float


class Metadata(BaseModel):
    total_processed: Annotated[float, pydantic.Field(alias="totalProcessed")]

    total_failed: Annotated[float, pydantic.Field(alias="totalFailed")]


class GetQueueStatusResponseTypedDict(TypedDict):
    r"""Queue Status"""

    main_queue: MainQueueTypedDict
    processing_queue: ProcessingQueueTypedDict
    dead_letter_queue: DeadLetterQueueTypedDict
    archive_queue: ArchiveQueueTypedDict
    metadata: MetadataTypedDict
    available_types: List[str]


class GetQueueStatusResponse(BaseModel):
    r"""Queue Status"""

    main_queue: Annotated[MainQueue, pydantic.Field(alias="mainQueue")]

    processing_queue: Annotated[
        ProcessingQueue, pydantic.Field(alias="processingQueue")
    ]

    dead_letter_queue: Annotated[
        DeadLetterQueue, pydantic.Field(alias="deadLetterQueue")
    ]

    archive_queue: Annotated[ArchiveQueue, pydantic.Field(alias="archiveQueue")]

    metadata: Metadata

    available_types: Annotated[List[str], pydantic.Field(alias="availableTypes")]
