"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class GetQueueMetricsResponseTypedDict(TypedDict):
    r"""Queue Metrics"""

    total_messages: float
    total_messages_processed: float
    total_messages_failed: float
    total_messages_acknowledged: float
    total_messages_requeued: float


class GetQueueMetricsResponse(BaseModel):
    r"""Queue Metrics"""

    total_messages: Annotated[float, pydantic.Field(alias="totalMessages")]

    total_messages_processed: Annotated[
        float, pydantic.Field(alias="totalMessagesProcessed")
    ]

    total_messages_failed: Annotated[float, pydantic.Field(alias="totalMessagesFailed")]

    total_messages_acknowledged: Annotated[
        float, pydantic.Field(alias="totalMessagesAcknowledged")
    ]

    total_messages_requeued: Annotated[
        float, pydantic.Field(alias="totalMessagesRequeued")
    ]
