"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from openapi.utils import FieldMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Any, List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class GetQueueMessagesRequestTypedDict(TypedDict):
    start_timestamp: str
    end_timestamp: str
    limit: NotRequired[str]


class GetQueueMessagesRequest(BaseModel):
    start_timestamp: Annotated[
        str,
        pydantic.Field(alias="startTimestamp"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]

    end_timestamp: Annotated[
        str,
        pydantic.Field(alias="endTimestamp"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]

    limit: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None


GetQueueMessagesPathTypedDict = TypeAliasType(
    "GetQueueMessagesPathTypedDict", Union[str, float]
)


GetQueueMessagesPath = TypeAliasType("GetQueueMessagesPath", Union[str, float])


class GetQueueMessagesIssueTypedDict(TypedDict):
    code: str
    path: List[GetQueueMessagesPathTypedDict]
    message: NotRequired[str]


class GetQueueMessagesIssue(BaseModel):
    code: str

    path: List[GetQueueMessagesPath]

    message: Optional[str] = None


class GetQueueMessagesErrorTypedDict(TypedDict):
    issues: List[GetQueueMessagesIssueTypedDict]
    name: str


class GetQueueMessagesError(BaseModel):
    issues: List[GetQueueMessagesIssue]

    name: str


class GetQueueMessagesResponseTypedDict(TypedDict):
    id: str
    type: str
    created_at: float
    attempt_count: float
    dequeued_at: Nullable[float]
    last_error: Nullable[str]
    processing_duration: float
    payload: NotRequired[Nullable[Any]]
    priority: NotRequired[float]


class GetQueueMessagesResponse(BaseModel):
    id: str

    type: str

    created_at: float

    attempt_count: float

    dequeued_at: Nullable[float]

    last_error: Nullable[str]

    processing_duration: float

    payload: OptionalNullable[Any] = UNSET

    priority: Optional[float] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["payload", "priority"]
        nullable_fields = ["payload", "dequeued_at", "last_error"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
