"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from typing_extensions import TypedDict


class GetQueueConfigResponseTypedDict(TypedDict):
    r"""Queue Configuration"""

    ack_timeout_seconds: float
    max_attempts: float
    batch_size: float
    enable_message_encryption: bool
    queue_name: str
    processing_queue_name: str
    dead_letter_queue_name: str
    archive_queue_name: str
    metadata_hash_name: str
    id_counter_key: str


class GetQueueConfigResponse(BaseModel):
    r"""Queue Configuration"""

    ack_timeout_seconds: float

    max_attempts: float

    batch_size: float

    enable_message_encryption: bool

    queue_name: str

    processing_queue_name: str

    dead_letter_queue_name: str

    archive_queue_name: str

    metadata_hash_name: str

    id_counter_key: str
