"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, List, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


class PostQueueMessageRequestTypedDict(TypedDict):
    r"""Queue Message"""

    type: str
    payload: NotRequired[Nullable[Any]]
    priority: NotRequired[float]
    custom_ack_timeout: NotRequired[float]


class PostQueueMessageRequest(BaseModel):
    r"""Queue Message"""

    type: str

    payload: OptionalNullable[Any] = UNSET

    priority: Optional[float] = None

    custom_ack_timeout: Optional[float] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["payload", "priority", "custom_ack_timeout"]
        nullable_fields = ["payload"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


PostQueueMessagePathTypedDict = TypeAliasType(
    "PostQueueMessagePathTypedDict", Union[str, float]
)


PostQueueMessagePath = TypeAliasType("PostQueueMessagePath", Union[str, float])


class PostQueueMessageIssueTypedDict(TypedDict):
    code: str
    path: List[PostQueueMessagePathTypedDict]
    message: NotRequired[str]


class PostQueueMessageIssue(BaseModel):
    code: str

    path: List[PostQueueMessagePath]

    message: Optional[str] = None


class PostQueueMessageErrorTypedDict(TypedDict):
    issues: List[PostQueueMessageIssueTypedDict]
    name: str


class PostQueueMessageError(BaseModel):
    issues: List[PostQueueMessageIssue]

    name: str


class PostQueueMessageResponseTypedDict(TypedDict):
    r"""Queue Message Added Successfully"""

    message: str


class PostQueueMessageResponse(BaseModel):
    r"""Queue Message Added Successfully"""

    message: str
