"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class PutQueueConfigRequestTypedDict(TypedDict):
    r"""Configuration Updates"""

    ack_timeout_seconds: NotRequired[float]
    max_attempts: NotRequired[float]
    batch_size: NotRequired[float]


class PutQueueConfigRequest(BaseModel):
    r"""Configuration Updates"""

    ack_timeout_seconds: Optional[float] = None

    max_attempts: Optional[float] = None

    batch_size: Optional[float] = None


class PutQueueConfigResponseTypedDict(TypedDict):
    r"""Updated Configuration"""

    ack_timeout_seconds: float
    max_attempts: float
    batch_size: float
    enable_message_encryption: bool
    queue_name: str
    processing_queue_name: str
    dead_letter_queue_name: str
    archive_queue_name: str
    metadata_hash_name: str
    id_counter_key: str


class PutQueueConfigResponse(BaseModel):
    r"""Updated Configuration"""

    ack_timeout_seconds: float

    max_attempts: float

    batch_size: float

    enable_message_encryption: bool

    queue_name: str

    processing_queue_name: str

    dead_letter_queue_name: str

    archive_queue_name: str

    metadata_hash_name: str

    id_counter_key: str
