"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class DeleteQueueQueueTypeClearQueueType(str, Enum):
    MAIN = "main"
    PROCESSING = "processing"
    DEAD = "dead"
    ARCHIVE = "archive"


class DeleteQueueQueueTypeClearRequestTypedDict(TypedDict):
    queue_type: DeleteQueueQueueTypeClearQueueType


class DeleteQueueQueueTypeClearRequest(BaseModel):
    queue_type: Annotated[
        DeleteQueueQueueTypeClearQueueType,
        pydantic.Field(alias="queueType"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]


class DeleteQueueQueueTypeClearResponseTypedDict(TypedDict):
    r"""Queue Cleared"""

    success: bool
    queue_type: str
    cleared_count: float
    message: str


class DeleteQueueQueueTypeClearResponse(BaseModel):
    r"""Queue Cleared"""

    success: bool

    queue_type: Annotated[str, pydantic.Field(alias="queueType")]

    cleared_count: Annotated[float, pydantic.Field(alias="clearedCount")]

    message: str
