"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, QueryParamMetadata
import pydantic
from typing import List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class DeleteQueueMessagesRequestTypedDict(TypedDict):
    start_timestamp: str
    end_timestamp: str


class DeleteQueueMessagesRequest(BaseModel):
    start_timestamp: Annotated[
        str,
        pydantic.Field(alias="startTimestamp"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]

    end_timestamp: Annotated[
        str,
        pydantic.Field(alias="endTimestamp"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]


DeleteQueueMessagesPathTypedDict = TypeAliasType(
    "DeleteQueueMessagesPathTypedDict", Union[str, float]
)


DeleteQueueMessagesPath = TypeAliasType("DeleteQueueMessagesPath", Union[str, float])


class DeleteQueueMessagesIssueTypedDict(TypedDict):
    code: str
    path: List[DeleteQueueMessagesPathTypedDict]
    message: NotRequired[str]


class DeleteQueueMessagesIssue(BaseModel):
    code: str

    path: List[DeleteQueueMessagesPath]

    message: Optional[str] = None


class DeleteQueueMessagesErrorTypedDict(TypedDict):
    issues: List[DeleteQueueMessagesIssueTypedDict]
    name: str


class DeleteQueueMessagesError(BaseModel):
    issues: List[DeleteQueueMessagesIssue]

    name: str


class DeleteQueueMessagesResponseTypedDict(TypedDict):
    r"""Messages Deleted"""

    message: str


class DeleteQueueMessagesResponse(BaseModel):
    r"""Messages Deleted"""

    message: str
