"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from typing_extensions import TypedDict


class GetHealthResponseTypedDict(TypedDict):
    r"""Health Check"""

    status: str


class GetHealthResponse(BaseModel):
    r"""Health Check"""

    status: str
