"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from openapi.utils import FieldMetadata, QueryParamMetadata, RequestMetadata
from pydantic import model_serializer
from typing import Any, List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class RequestBodyTypedDict(TypedDict):
    type: str
    payload: NotRequired[Nullable[Any]]
    priority: NotRequired[float]
    custom_ack_timeout: NotRequired[float]


class RequestBody(BaseModel):
    type: str

    payload: OptionalNullable[Any] = UNSET

    priority: Optional[float] = None

    custom_ack_timeout: Optional[float] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["payload", "priority", "custom_ack_timeout"]
        nullable_fields = ["payload"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


class PostQueueBatchRequestTypedDict(TypedDict):
    request_body: List[RequestBodyTypedDict]
    r"""Queue Message"""
    custom_ack_timeout: NotRequired[float]


class PostQueueBatchRequest(BaseModel):
    request_body: Annotated[
        List[RequestBody],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Queue Message"""

    custom_ack_timeout: Annotated[
        Optional[float],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None


PostQueueBatchPathTypedDict = TypeAliasType(
    "PostQueueBatchPathTypedDict", Union[str, float]
)


PostQueueBatchPath = TypeAliasType("PostQueueBatchPath", Union[str, float])


class PostQueueBatchIssueTypedDict(TypedDict):
    code: str
    path: List[PostQueueBatchPathTypedDict]
    message: NotRequired[str]


class PostQueueBatchIssue(BaseModel):
    code: str

    path: List[PostQueueBatchPath]

    message: Optional[str] = None


class PostQueueBatchErrorTypedDict(TypedDict):
    issues: List[PostQueueBatchIssueTypedDict]
    name: str


class PostQueueBatchError(BaseModel):
    issues: List[PostQueueBatchIssue]

    name: str


class PostQueueBatchResponseTypedDict(TypedDict):
    r"""Batch Added Successfully"""

    message: str


class PostQueueBatchResponse(BaseModel):
    r"""Batch Added Successfully"""

    message: str
