"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, List, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


class PostQueueAckRequestTypedDict(TypedDict):
    r"""Acknowledged Message"""

    id: str
    type: NotRequired[str]
    payload: NotRequired[Nullable[Any]]
    created_at: NotRequired[float]
    priority: NotRequired[float]
    attempt_count: NotRequired[float]
    dequeued_at: NotRequired[Nullable[float]]
    last_error: NotRequired[Nullable[str]]
    processing_duration: NotRequired[float]


class PostQueueAckRequest(BaseModel):
    r"""Acknowledged Message"""

    id: str

    type: Optional[str] = None

    payload: OptionalNullable[Any] = UNSET

    created_at: Optional[float] = None

    priority: Optional[float] = None

    attempt_count: Optional[float] = None

    dequeued_at: OptionalNullable[float] = UNSET

    last_error: OptionalNullable[str] = UNSET

    processing_duration: Optional[float] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "type",
            "payload",
            "created_at",
            "priority",
            "attempt_count",
            "dequeued_at",
            "last_error",
            "processing_duration",
        ]
        nullable_fields = ["payload", "dequeued_at", "last_error"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


PostQueueAckPathTypedDict = TypeAliasType(
    "PostQueueAckPathTypedDict", Union[str, float]
)


PostQueueAckPath = TypeAliasType("PostQueueAckPath", Union[str, float])


class PostQueueAckIssueTypedDict(TypedDict):
    code: str
    path: List[PostQueueAckPathTypedDict]
    message: NotRequired[str]


class PostQueueAckIssue(BaseModel):
    code: str

    path: List[PostQueueAckPath]

    message: Optional[str] = None


class PostQueueAckErrorTypedDict(TypedDict):
    issues: List[PostQueueAckIssueTypedDict]
    name: str


class PostQueueAckError(BaseModel):
    issues: List[PostQueueAckIssue]

    name: str


class PostQueueAckResponseTypedDict(TypedDict):
    r"""Message Acknowledged"""

    message: str


class PostQueueAckResponse(BaseModel):
    r"""Message Acknowledged"""

    message: str
