"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from openapi.errors import SDKError
from openapi.types import BaseModel
from typing import Optional


class DeleteQueueMessageMessageIDInternalServerErrorData(BaseModel):
    message: str


class DeleteQueueMessageMessageIDInternalServerError(SDKError):
    r"""Internal Server Error"""

    data: DeleteQueueMessageMessageIDInternalServerErrorData

    def __init__(
        self,
        data: DeleteQueueMessageMessageIDInternalServerErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data


class DeleteQueueMessageMessageIDNotFoundErrorData(BaseModel):
    message: str


class DeleteQueueMessageMessageIDNotFoundError(SDKError):
    r"""Message not found"""

    data: DeleteQueueMessageMessageIDNotFoundErrorData

    def __init__(
        self,
        data: DeleteQueueMessageMessageIDNotFoundErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data


class DeleteQueueMessageMessageIDBadRequestErrorData(BaseModel):
    message: str


class DeleteQueueMessageMessageIDBadRequestError(SDKError):
    r"""Bad Request"""

    data: DeleteQueueMessageMessageIDBadRequestErrorData

    def __init__(
        self,
        data: DeleteQueueMessageMessageIDBadRequestErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data
