"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from openapi.errors import SDKError
from openapi.models import delete_queue_messagesop as models_delete_queue_messagesop
from openapi.types import BaseModel
from typing import Optional


class DeleteQueueMessagesUnprocessableEntityErrorData(BaseModel):
    success: bool

    error: models_delete_queue_messagesop.DeleteQueueMessagesError


class DeleteQueueMessagesUnprocessableEntityError(SDKError):
    r"""Validation Error"""

    data: DeleteQueueMessagesUnprocessableEntityErrorData

    def __init__(
        self,
        data: DeleteQueueMessagesUnprocessableEntityErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        self.data = data
