"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from openapi.errors import SDKError
from openapi.types import BaseModel
from typing import Optional


class GetQueueConfigInternalServerErrorData(BaseModel):
    message: str


class GetQueueConfigInternalServerError(SDKError):
    r"""Internal Server Error"""

    data: GetQueueConfigInternalServerErrorData

    def __init__(
        self,
        data: GetQueueConfigInternalServerErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data
