"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from openapi.errors import SDKError
from openapi.models import post_queue_ackop as models_post_queue_ackop
from openapi.types import BaseModel
from typing import Optional


class PostQueueAckUnprocessableEntityErrorData(BaseModel):
    success: bool

    error: models_post_queue_ackop.PostQueueAckError


class PostQueueAckUnprocessableEntityError(SDKError):
    r"""Validation Error"""

    data: PostQueueAckUnprocessableEntityErrorData

    def __init__(
        self,
        data: PostQueueAckUnprocessableEntityErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        self.data = data


class PostQueueAckBadRequestErrorData(BaseModel):
    message: str


class PostQueueAckBadRequestError(SDKError):
    r"""Message not acknowledged"""

    data: PostQueueAckBadRequestErrorData

    def __init__(
        self,
        data: PostQueueAckBadRequestErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data
