"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from openapi.errors import SDKError
from openapi.models import post_queue_messageop as models_post_queue_messageop
from openapi.types import BaseModel
from typing import Optional


class PostQueueMessageInternalServerErrorData(BaseModel):
    message: str


class PostQueueMessageInternalServerError(SDKError):
    r"""Internal Server Error"""

    data: PostQueueMessageInternalServerErrorData

    def __init__(
        self,
        data: PostQueueMessageInternalServerErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data


class PostQueueMessageUnprocessableEntityErrorData(BaseModel):
    success: bool

    error: models_post_queue_messageop.PostQueueMessageError


class PostQueueMessageUnprocessableEntityError(SDKError):
    r"""Validation Error"""

    data: PostQueueMessageUnprocessableEntityErrorData

    def __init__(
        self,
        data: PostQueueMessageUnprocessableEntityErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        self.data = data
