"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from openapi.errors import SDKError
from openapi.types import BaseModel
from typing import Optional


class PutQueueConfigInternalServerErrorData(BaseModel):
    message: str


class PutQueueConfigInternalServerError(SDKError):
    r"""Internal Server Error"""

    data: PutQueueConfigInternalServerErrorData

    def __init__(
        self,
        data: PutQueueConfigInternalServerErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data


class PutQueueConfigBadRequestErrorData(BaseModel):
    message: str


class PutQueueConfigBadRequestError(SDKError):
    r"""Validation Error"""

    data: PutQueueConfigBadRequestErrorData

    def __init__(
        self,
        data: PutQueueConfigBadRequestErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data
