// Test: Fail_Create_Message_Missing_Type
// Generated by Rohan

import http from 'k6/http';
import { check } from 'k6';

const BASE_URL = __ENV.BASE_URL || 'http://localhost:8080';

export default function() {
    const res = http.post(`${BASE_URL}/messages`, JSON.stringify({ content: 'test' }), {
        headers: { 'Content-Type': 'application/json' }
    });
    check(res, { 'status is 4xx': (r) => r.status >= 400 && r.status < 500 });
}