// Test: Get_Messages_Limit_5
// Generated by Rohan

import http from 'k6/http';
import { check } from 'k6';

const BASE_URL = __ENV.BASE_URL || 'http://localhost:8080';

export default function() {
    const res = http.get(`${BASE_URL}/messages?limit=5`);
    check(res, { 'status is 200': (r) => r.status === 200 });
}