// Test: Delete_Message_Basic
// Generated by Rohan

import http from 'k6/http';
import { check } from 'k6';

const BASE_URL = __ENV.BASE_URL || 'http://localhost:8080';

export default function() {
    const res = http.del(`${BASE_URL}/messages/123`);
    check(res, { 'status is 204': (r) => r.status === 204 });
}