// Test: Fail_Get_Messages_Negative_Limit
// Generated by Rohan

import http from 'k6/http';
import { check } from 'k6';

const BASE_URL = __ENV.BASE_URL || 'http://localhost:8080';

export default function() {
    const res = http.get(`${BASE_URL}/messages?limit=-1`);
    check(res, { 'status is 4xx': (r) => r.status >= 400 && r.status < 500 });
}