// Test: Create_Message_Negative_Limit
// Generated by Rohan

import http from 'k6/http';
import { check } from 'k6';

const BASE_URL = __ENV.BASE_URL || 'http://localhost:8080';

export default function() {
    const res = http.post(`${BASE_URL}/messages`, JSON.stringify({ limit: -1 }), {
        headers: { 'Content-Type': 'application/json' }
    });
    check(res, { 'status is 400': (r) => r.status === 400 });
}