"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import TYPE_CHECKING
from importlib import import_module
import builtins

if TYPE_CHECKING:
    from .apierror import APIError
    from .delete_queue_message_messageid_op import (
        DeleteQueueMessageMessageIDBadRequestError,
        DeleteQueueMessageMessageIDBadRequestErrorData,
        DeleteQueueMessageMessageIDInternalServerError,
        DeleteQueueMessageMessageIDInternalServerErrorData,
        DeleteQueueMessageMessageIDNotFoundError,
        DeleteQueueMessageMessageIDNotFoundErrorData,
    )
    from .delete_queue_messagesop import (
        DeleteQueueMessagesUnprocessableEntityError,
        DeleteQueueMessagesUnprocessableEntityErrorData,
    )
    from .delete_queue_queuetype_clearop import (
        DeleteQueueQueueTypeClearBadRequestError,
        DeleteQueueQueueTypeClearBadRequestErrorData,
        DeleteQueueQueueTypeClearInternalServerError,
        DeleteQueueQueueTypeClearInternalServerErrorData,
    )
    from .get_healthop import (
        GetHealthInternalServerError,
        GetHealthInternalServerErrorData,
    )
    from .get_queue_configop import (
        GetQueueConfigInternalServerError,
        GetQueueConfigInternalServerErrorData,
    )
    from .get_queue_messageop import (
        GetQueueMessageNotFoundError,
        GetQueueMessageNotFoundErrorData,
        GetQueueMessageUnprocessableEntityError,
        GetQueueMessageUnprocessableEntityErrorData,
    )
    from .get_queue_messagesop import (
        GetQueueMessagesUnprocessableEntityError,
        GetQueueMessagesUnprocessableEntityErrorData,
    )
    from .no_response_error import NoResponseError
    from .post_queue_ackop import (
        PostQueueAckBadRequestError,
        PostQueueAckBadRequestErrorData,
        PostQueueAckUnprocessableEntityError,
        PostQueueAckUnprocessableEntityErrorData,
    )
    from .post_queue_batchop import (
        PostQueueBatchUnprocessableEntityError,
        PostQueueBatchUnprocessableEntityErrorData,
    )
    from .post_queue_messageop import (
        PostQueueMessageInternalServerError,
        PostQueueMessageInternalServerErrorData,
        PostQueueMessageUnprocessableEntityError,
        PostQueueMessageUnprocessableEntityErrorData,
    )
    from .put_queue_configop import (
        PutQueueConfigBadRequestError,
        PutQueueConfigBadRequestErrorData,
        PutQueueConfigInternalServerError,
        PutQueueConfigInternalServerErrorData,
    )
    from .responsevalidationerror import ResponseValidationError
    from .sdkerror import SDKError

__all__ = [
    "APIError",
    "DeleteQueueMessageMessageIDBadRequestError",
    "DeleteQueueMessageMessageIDBadRequestErrorData",
    "DeleteQueueMessageMessageIDInternalServerError",
    "DeleteQueueMessageMessageIDInternalServerErrorData",
    "DeleteQueueMessageMessageIDNotFoundError",
    "DeleteQueueMessageMessageIDNotFoundErrorData",
    "DeleteQueueMessagesUnprocessableEntityError",
    "DeleteQueueMessagesUnprocessableEntityErrorData",
    "DeleteQueueQueueTypeClearBadRequestError",
    "DeleteQueueQueueTypeClearBadRequestErrorData",
    "DeleteQueueQueueTypeClearInternalServerError",
    "DeleteQueueQueueTypeClearInternalServerErrorData",
    "GetHealthInternalServerError",
    "GetHealthInternalServerErrorData",
    "GetQueueConfigInternalServerError",
    "GetQueueConfigInternalServerErrorData",
    "GetQueueMessageNotFoundError",
    "GetQueueMessageNotFoundErrorData",
    "GetQueueMessageUnprocessableEntityError",
    "GetQueueMessageUnprocessableEntityErrorData",
    "GetQueueMessagesUnprocessableEntityError",
    "GetQueueMessagesUnprocessableEntityErrorData",
    "NoResponseError",
    "PostQueueAckBadRequestError",
    "PostQueueAckBadRequestErrorData",
    "PostQueueAckUnprocessableEntityError",
    "PostQueueAckUnprocessableEntityErrorData",
    "PostQueueBatchUnprocessableEntityError",
    "PostQueueBatchUnprocessableEntityErrorData",
    "PostQueueMessageInternalServerError",
    "PostQueueMessageInternalServerErrorData",
    "PostQueueMessageUnprocessableEntityError",
    "PostQueueMessageUnprocessableEntityErrorData",
    "PutQueueConfigBadRequestError",
    "PutQueueConfigBadRequestErrorData",
    "PutQueueConfigInternalServerError",
    "PutQueueConfigInternalServerErrorData",
    "ResponseValidationError",
    "SDKError",
]

_dynamic_imports: dict[str, str] = {
    "APIError": ".apierror",
    "DeleteQueueMessageMessageIDBadRequestError": ".delete_queue_message_messageid_op",
    "DeleteQueueMessageMessageIDBadRequestErrorData": ".delete_queue_message_messageid_op",
    "DeleteQueueMessageMessageIDInternalServerError": ".delete_queue_message_messageid_op",
    "DeleteQueueMessageMessageIDInternalServerErrorData": ".delete_queue_message_messageid_op",
    "DeleteQueueMessageMessageIDNotFoundError": ".delete_queue_message_messageid_op",
    "DeleteQueueMessageMessageIDNotFoundErrorData": ".delete_queue_message_messageid_op",
    "DeleteQueueMessagesUnprocessableEntityError": ".delete_queue_messagesop",
    "DeleteQueueMessagesUnprocessableEntityErrorData": ".delete_queue_messagesop",
    "DeleteQueueQueueTypeClearBadRequestError": ".delete_queue_queuetype_clearop",
    "DeleteQueueQueueTypeClearBadRequestErrorData": ".delete_queue_queuetype_clearop",
    "DeleteQueueQueueTypeClearInternalServerError": ".delete_queue_queuetype_clearop",
    "DeleteQueueQueueTypeClearInternalServerErrorData": ".delete_queue_queuetype_clearop",
    "GetHealthInternalServerError": ".get_healthop",
    "GetHealthInternalServerErrorData": ".get_healthop",
    "GetQueueConfigInternalServerError": ".get_queue_configop",
    "GetQueueConfigInternalServerErrorData": ".get_queue_configop",
    "GetQueueMessageNotFoundError": ".get_queue_messageop",
    "GetQueueMessageNotFoundErrorData": ".get_queue_messageop",
    "GetQueueMessageUnprocessableEntityError": ".get_queue_messageop",
    "GetQueueMessageUnprocessableEntityErrorData": ".get_queue_messageop",
    "GetQueueMessagesUnprocessableEntityError": ".get_queue_messagesop",
    "GetQueueMessagesUnprocessableEntityErrorData": ".get_queue_messagesop",
    "NoResponseError": ".no_response_error",
    "PostQueueAckBadRequestError": ".post_queue_ackop",
    "PostQueueAckBadRequestErrorData": ".post_queue_ackop",
    "PostQueueAckUnprocessableEntityError": ".post_queue_ackop",
    "PostQueueAckUnprocessableEntityErrorData": ".post_queue_ackop",
    "PostQueueBatchUnprocessableEntityError": ".post_queue_batchop",
    "PostQueueBatchUnprocessableEntityErrorData": ".post_queue_batchop",
    "PostQueueMessageInternalServerError": ".post_queue_messageop",
    "PostQueueMessageInternalServerErrorData": ".post_queue_messageop",
    "PostQueueMessageUnprocessableEntityError": ".post_queue_messageop",
    "PostQueueMessageUnprocessableEntityErrorData": ".post_queue_messageop",
    "PutQueueConfigBadRequestError": ".put_queue_configop",
    "PutQueueConfigBadRequestErrorData": ".put_queue_configop",
    "PutQueueConfigInternalServerError": ".put_queue_configop",
    "PutQueueConfigInternalServerErrorData": ".put_queue_configop",
    "ResponseValidationError": ".responsevalidationerror",
    "SDKError": ".sdkerror",
}


def __getattr__(attr_name: str) -> object:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__} "
        )

    try:
        module = import_module(module_name, __package__)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = builtins.list(_dynamic_imports.keys())
    return builtins.sorted(lazy_attrs)
