"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from openapi.errors import SDKError
from openapi.models import get_queue_messagesop as models_get_queue_messagesop
from openapi.types import BaseModel
from typing import Optional


class GetQueueMessagesUnprocessableEntityErrorData(BaseModel):
    success: bool

    error: models_get_queue_messagesop.GetQueueMessagesError


class GetQueueMessagesUnprocessableEntityError(SDKError):
    r"""Validation Error"""

    data: GetQueueMessagesUnprocessableEntityErrorData

    def __init__(
        self,
        data: GetQueueMessagesUnprocessableEntityErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        self.data = data
