"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from openapi.errors import SDKError
from openapi.types import BaseModel
from typing import Optional


class GetHealthInternalServerErrorData(BaseModel):
    status: str


class GetHealthInternalServerError(SDKError):
    r"""Internal Server Error"""

    data: GetHealthInternalServerErrorData

    def __init__(
        self,
        data: GetHealthInternalServerErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        self.data = data
