"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from openapi.errors import SDKError
from openapi.models import get_queue_messageop as models_get_queue_messageop
from openapi.types import BaseModel
from typing import Optional


class GetQueueMessageUnprocessableEntityErrorData(BaseModel):
    success: bool

    error: models_get_queue_messageop.GetQueueMessageError


class GetQueueMessageUnprocessableEntityError(SDKError):
    r"""Validation Error"""

    data: GetQueueMessageUnprocessableEntityErrorData

    def __init__(
        self,
        data: GetQueueMessageUnprocessableEntityErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        self.data = data


class GetQueueMessageNotFoundErrorData(BaseModel):
    message: str


class GetQueueMessageNotFoundError(SDKError):
    r"""Message not found"""

    data: GetQueueMessageNotFoundErrorData

    def __init__(
        self,
        data: GetQueueMessageNotFoundErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data
