"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from openapi.errors import SDKError
from openapi.models import post_queue_batchop as models_post_queue_batchop
from openapi.types import BaseModel
from typing import Optional


class PostQueueBatchUnprocessableEntityErrorData(BaseModel):
    success: bool

    error: models_post_queue_batchop.PostQueueBatchError


class PostQueueBatchUnprocessableEntityError(SDKError):
    r"""Validation Error"""

    data: PostQueueBatchUnprocessableEntityErrorData

    def __init__(
        self,
        data: PostQueueBatchUnprocessableEntityErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        self.data = data
